### ISSUE TITLE
Request: Deduplication of results.

### ISSUE THREAD

**Issue by Eric-Hacker** [moisseev/received#5]
Thank you for this plugin. It works great for my particular use case of parsing the headers to find the original email address the email was sent to. The only issue is that the for information is often duplicated in the headers, so I get multiple lines that match and get displayed in the email. Usually it is only 2 or 3 duplicated, so it is not a big deal. 

My Regular Expression is: `for (.+?erichacker\.com>)`

Here is a screenshot:
![image](https://user-images.githubusercontent.com/27235562/150876129-5fc39ec5-1963-4995-a80a-1c87909b6667.png)

This need may seem odd, but I have a catch-all domain mailbox and I give every commercial organization their own email address so I will know when they get compromised or sell my address to someone else. I wasn't paying good attention though, until I set up your plugin. Now I can easily check all the email. 

Thanks

**Comment by Nothing4You** [comment]
i'm using it for a similar purpose, as i'm running my own mail server i can easily solve this by only checking for the received header containing my mailserver's name:

```
^from (.+?) by my\.mail\.server\b.+( ).+(for )<(.+)>(?:; .+)$
```

it might be a useful setting though to stop after the first n matches.

**Comment by moisseev** [comment]
> it might be a useful setting though to stop after the first n matches.

It is doable, but I am not sure if it is useful to display the first N matches or the Nth match.
- I believe generally only certain Received header is of interest.
- It will not work even if N=1. In most cases the first (last added) Received header is a LMTP hop.
- The sequence number of the interesting Received header may vary due to different mail delivery paths.

**Comment by Eric-Hacker** [comment]
I like and tried the suggestion from Nothing4You. It works and I'll just hope that my service provider doesn't change inbound mail server name all that often. Worst case is that I have to adjust the regex from time to time.

I agree with moisseev that given the headers are stacked LIFO, trying to get to the header one wants by counting will likely fail in some situations. 

I'm going to close the issue. Thanks for your help!

**Comment by Nothing4You** [comment]
>     * I believe generally only certain Received header is of interest.
>     * It will not work even if N=1. In most cases the first (last added) Received header is a LMTP hop.
>     * The sequence number of the interesting Received header may vary due to different mail delivery paths.

at least for me, I only care about the very first header in the list, which is my own mail server.
this reports to me which local recipient the message was received for and which external server it was received from.
since i don't send mails between multiple mail servers I'm sure that this is always the first received header.
for managed email you typically don't know this/can't rely on this, but if you know your setup this should be safe to use.
